// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iighazifldupctjzcjce.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlpZ2hhemlmbGR1cGN0anpjamNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk5OTQwNDksImV4cCI6MjA1NTU3MDA0OX0.WjqzP9qX38ZWmzszArLX2n7p6GcaLgPqgDy03t-bAMo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);